dependencies:
  - python=3
  - pip:
    - tensorflow
    - caffe
    - functools
    - math
    - time
    - sys
    - six
    - argparse
    - tarfile
    - random
    - os
    - xml
    - __future__
    - collections
    - enum 
    - pprint
    - deployment 
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
